name: JortooCore
version: '${project.version}'
main: me.jqrtox.jortoocore.JortooCore
api-version: '1.21'
loadbefore:
  - WorldGuard
commands:
  clearlag:
    permission: "jortoo.admin.clearlag"
    aliases: ["clag", "cl"]
  craft:
    permission: "jortoo.craft"
  anvil:
    permission: "jortoo.anvil"
  cartography:
    permission: "jortoo.cartography"
  grindstone:
    permission: "jortoo.grindstone"
  loom:
    permission: "jortoo.loom"
  smithingtable:
    permission: "jortoo.smithingtable"
  stonecutter:
    permission: "jortoo.stonecutter"
  clearchat:
    permission: "jortoo.staff.clearchat"
    aliases: ["cc"]
  heal:
    permission: "jortoo.heal"
    override: true
  feed:
    permission: "jortoo.feed"
    override: true
  god:
    aliases: ["godmode"]
    permission: "jortoo.god"
  broadcast:
    aliases: ["bc", "bcast", "broadc"]
    permission: "jortoo.staff.broadcast"
  fly:
    aliases: ["flight"]
    permission: "jortoo.fly"
  vanish:
    aliases: ["v"]
    permission: "jortoo.staff.vanish"
  hat:
    aliases: ["head"]
    permission: "jortoo.hat"
  spawn:
  setspawn:
    permission: "jortoo.staff.setspawn"
